# Generated by Django 4.2.1 on 2023-06-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Createuser',
            new_name='Create',
        ),
    ]
