# Generated by Django 4.2.1 on 2023-06-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_createuser_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='email',
            new_name='ToDo',
        ),
        migrations.RenameField(
            model_name='create',
            old_name='name',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='create',
            old_name='username',
            new_name='week',
        ),
    ]
