# Generated by Django 4.2.1 on 2023-06-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_create_todo_rename_name_create_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='choices',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
